// <auto-generated />
namespace DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newversion106 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newversion106));
        
        string IMigrationMetadata.Id
        {
            get { return "201506100901402_newversion106"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
