// <auto-generated />
namespace DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fiveMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fiveMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201504271658193_fiveMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
